# the program to run
program: run_train_smiles_single.py

# project the sweep is part of
project: protein-lig-sedd
entity: noor-harwell-howard-university

# method for hyperparameter search 
method: random

# metric to optimize
metric:
  name: evaluation_loss
  goal: minimize

# parameter space to search
parameters:
  hidden_size:
    values: [1024, 2048, 4096]
  n_blocks:
    values: [8, 16]
  n_heads:
    values: [8, 12, 16]
  lr:
      min: 1e-5
      max: 5e-4
      distribution: log_uniform
  weight_decay:
    values: [0, 0.01]
  batch_size:
    values: [4, 8, 16, 32]
  grad_clip:
    values: [0.5, 1.0, 2.0]
  epochs: 
    values: [10, 20, 30, 40, 50]

early_terminate:
  type: hyperband
  min_iter: 5
 

# CLI command to initialize sweep (next line will output SWEEP_ID)
  # wandb sweep sweep_config.yaml

# CLI command to start sweep
  # wandb wandb agent SWEEP_ID











# possible parameters
# parameters:
#   weight_decay: 
#     value: 0
#   optimizer:
#     value: AdamW
#   lr:
#     value: 3e-4
#   beta1: 
#     value: 0.9
#   beta2: 
#     value: 0.999
#   eps:
#     value: 1e-8
#   warmup: 
#     value: 1000
#   grad_clip:
#     value: 1.
#   batch_size:
#     values: [4, 8]
#   accum:
#     value: 1
#   n_iters:
#     value: 200
#   snapshot_freq:
#     value: 200
#   log_freq:
#     value: 50
#   eval_freq:
#     value: 50
#   snapshot_freq_for_preemption:
#     value: 200
#   weight:
#     value: standard
#   snapshot_sampling:
#     value: True
#   ema:
#     value: 0.9999
