work_dir: /eagle/FoundEpidem/avasan/IDEAL/DiffusionModels/protein_lig_sedd

model:
  name: medium           
  type: ddit
  hidden_size: 1024 #768
  cond_dim: 128 #512 #28
  length: 1224 #36 #128
  n_blocks: 8
  n_heads: 16
  scale_by_sigma: True
  dropout: 0.1
  esm_dim: 640 #332 #1024
  molformer_dim: 768

defaults:
  - _self_
  - model: tiny

ngpus: 1
tokens: 2396 #39 #25

training:
  batch_size: 32
  accum: 1
  epochs: 10
  max_samples: 1000000
  num_workers: 1
  seed: 42
  force_reprocess: False
  n_iters: 10000000 #10_000
  snapshot_freq: 200 #1_000
  log_freq: 50
  eval_freq: 200
  snapshot_freq_for_preemption: 200
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  train: acyp
  valid: acyp
  cache_dir: data
  train_ratio: 0.8
  val_ratio: 0.1
  max_protein_len: 1024
  max_ligand_len: 128
  use_structure: False

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: cosine #loglinear #geometric #
  sigma_min: !!float "1e-3"
  sigma_max: 1
  eps: !!float "0.1"
sampling:
  predictor: euler
  steps: 25
  noise_removal: True

eval:
  batch_size: 25
  perplexity: True
  perplexity_batch_size: 4

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: !!float "3e-4"
  beta1: 0.9
  beta2: 0.999
  eps: !!float "1e-8"
  warmup: 1000 #1_000
  grad_clip: 1.

hydra:
  run:
    dir: exp_local/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  
